backend:
  name: git-gateway
  branch: main

media_folder: "static/images/uploads"
public_folder: "/images/uploads"

collections:
  - name: "blog"
    label: "Blog"
    folder: "content/en/blog"
    create: true
    slug: "{{slug}}/index.md"
    fields:
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Publish Date", name: "date", widget: "datetime"}
      - {label: "Last Modified", name: "lastmod", widget: "datetime"}
      - {label: "Description", name: "description", widget: "string"}
      - {label: "Excerpt", name: "excerpt", widget: "string"}
      - {label: "Draft", name: "draft", widget: "hidden", default: false}
      - {label: "Pinned", name: "pinned", widget: "hidden", default: false}
      - {label: "Homepage", name: "homepage", widget: "hidden", default: false}
      - {label: "Body", name: "body", widget: "markdown"}

