collections:
  - name: "projects" # Used in routes, e.g., /admin/collections/projects
    label: "Projects" # Used in the UI
    folder: "src/content/projects" # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    fields: # The fields for each document, usually in frontmatter
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Repository URL", name: "repo", widget: "string" }
      - { label: "Description", name: "description", widget: "string" }
      - { label: "Body", name: "body", widget: "markdown" }

media_folder: "/public" # Location where files will be stored in the repo
public_folder: "/" # The src attribute for uploaded media

backend:
  name: git-gateway
  branch: main